PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE products (     id INTEGER PRIMARY KEY AUTOINCREMENT,     name TEXT NOT NULL,     highlight TEXT,     desc TEXT,     img TEXT,     items TEXT,     patent TEXT,     patent_no TEXT , img_home TEXT DEFAULT '', updated_by TEXT, updated_at TEXT);
INSERT INTO "products" ("id","name","highlight","desc","img","items","patent","patent_no","img_home","updated_by","updated_at") VALUES(1,'Scale Sheet (Tare Sheet)','專利單張抽取設計｜取用便利・不易污染・衛生安心','結合專利技術打造的抽取式 Scale Sheet，突破傳統取用方式的繁瑣與不便。採用貼心的單張抽取設計，取用俐落、操作便利，不僅能提升作業效率、節省取用時間，更能有效控管使用成本。材質強韌、防沾黏且不易受污染，適用於生鮮秤重、餐飲備料、工業分裝及各大商場櫃台等多元作業場景，是追求高效率、衛生與便利性的專業首選。','/media/Scale%20Sheet.webp','專利證書、防沾黏、不受汙染','/media/Patent.webp','','/media/%E5%B0%81%E9%9D%A2-Scale%20Sheet.webp','admin','2026-09-10T06:34:38.990Z');
INSERT INTO "products" ("id","name","highlight","desc","img","items","patent","patent_no","img_home","updated_by","updated_at") VALUES(2,'耐熱袋','食品級，守護食材新鮮與衛生','專為生鮮食品與日常零售打造的優質耐熱袋系列。嚴選食品級合格原料，質地安全、無毒無味，具備極佳的抗拉韌性。提供平裝、捲裝等多樣化規格，搭配耐熱袋、雙道封口食品袋及市場專用袋等多元選擇，有效鎖住食材水分與鮮度，為消費者與商家嚴格把關每一道飲食安全防線。','/media/%E8%94%AC%E6%9E%9C%E8%A2%8B.webp','食品袋、市場袋、冰袋、雙道封口袋','','','/media/%E5%B0%81%E9%9D%A2-%E8%94%AC%E6%9E%9C%E8%A2%8B.webp','admin','2026-09-10T06:40:44.146Z');
INSERT INTO "products" ("id","name","highlight","desc","img","items","patent","patent_no","img_home","updated_by","updated_at") VALUES(3,'清潔袋','強韌耐穿刺、絕不漏水的日常清潔袋首選','依託台塑高品質原料自製優勢，經由嘉義新港廠區自動化精密吹膜與封口技術打造。全系列涵蓋連捲式、單張抽取式及國家環保標章認證清潔袋等多種款式。具備超強的抗拉張力與優異承重力，不論是用於一般家庭日常垃圾清運，或是辦公大樓、餐飲旅宿等高頻率商用場域，皆能輕鬆應對、安心不破漏。','/media/%E6%B8%85%E6%BD%94%E8%A2%8B.webp','連捲、單張抽取、八折袋、環保清潔袋','','','/media/%E5%B0%81%E9%9D%A2-%E6%B8%85%E6%BD%94%E8%A2%8B.webp','admin','2026-09-10T06:42:20.573Z');
INSERT INTO "products" ("id","name","highlight","desc","img","items","patent","patent_no","img_home","updated_by","updated_at") VALUES(4,'拉繩清潔袋','一拉即束口，減少蚊蠅孳生，容量大升級增加 30% 、乾淨不沾手','專為現代便利生活與高效清潔設計的貼心之作。一體成型的堅固拉繩結構，讓您輕鬆一拉即可俐落束口，有效避免清理時垃圾外漏與雙手沾染髒汙的困擾。特殊設計使內部空間有效利用率增加 30% 以上，並能緊密鎖住異味不外散；另提供醫療級與環保拉繩款式，讓居家與商辦環境更顯潔淨衛生。','/media/%E6%8B%89%E7%B9%A9%E8%A2%8B1.webp','拉繩清潔袋、拉繩醫療袋、環保拉繩清潔袋','','','/media/%E5%B0%81%E9%9D%A2-%E6%8B%89%E7%B9%A9%E8%A2%8B.webp','admin','2026-09-10T08:42:03.023Z');
INSERT INTO "products" ("id","name","highlight","desc","img","items","patent","patent_no","img_home","updated_by","updated_at") VALUES(5,'多功能手套','親膚舒適、防護俐落的萬用防護手套','兼具極佳彈性與細緻觸感的多功能手套系列。表面採特殊內壓紋設計，不僅穿脫滑順、不沾黏，更具備良好的防滑抓握力。全系列符合無粉末、無乳膠等友善肌膚標準，無論是用於餐飲調理、食品加工、日常清潔打掃或居家照護，皆能提供全方位且靈活舒適的衛生防護體驗。','/media/%E5%A4%9A%E5%8A%9F%E8%83%BD%E6%89%8B%E5%A5%97.webp','無粉末、無乳膠、內壓紋、易穿脫、彈性優、觸感佳','','','/media/%E5%B0%81%E9%9D%A2-%E5%A4%9A%E5%8A%9F%E8%83%BD%E6%89%8B%E5%A5%97.webp','sales','2026-09-09T04:18:13.332Z');
INSERT INTO "products" ("id","name","highlight","desc","img","items","patent","patent_no","img_home","updated_by","updated_at") VALUES(6,'夾鏈袋','密封緊密，完美保鮮','採用高標準工藝打造的重覆使用夾鏈袋系列。袋身厚實、手感紮實，搭配密合度極佳的雙軌或單軌夾鏈結構，具備優異的氣密與防潮表現。不論是生鮮食材冷凍保鮮、日常小物分類收納，或是工業零件包裝，皆能提供卓越的密封保護，支援多次重複開合依然緊密如初。','/media/%E5%A4%BE%E9%8F%88%E8%A2%8B.webp','密實袋、冷凍袋、由任袋、立式夾鏈袋(可直立)','','','/media/%E5%B0%81%E9%9D%A2-%E5%A4%BE%E9%8F%88%E8%A2%8B.webp','admin','2026-09-10T06:49:53.851Z');
INSERT INTO "products" ("id","name","highlight","desc","img","items","patent","patent_no","img_home","updated_by","updated_at") VALUES(7,'遮蔽防塵膠帶','施工裝潢與日常防塵的省時利器','集膠帶與防塵膜於一體的便利防護方案。專為室內裝潢、噴漆粉刷、居家裝修及醫療消毒防護設計，能夠快速且大面積地覆蓋並保護傢俱、地板與牆面免受粉塵、油漆噴濺汙染。黏貼穩固且撕除不留殘膠，大幅簡化施工前的遮蔽前置作業，兼具高效率與完美防護效果。','/media/%E5%8F%B0%E5%A1%91%E9%81%AE%E8%94%BD%E9%98%B2%E5%A1%B5%E8%86%A0%E5%B8%B6.webp','遮蔽保護、消毒防護、覆蓋防塵、施工便利','','','/media/%E5%B0%81%E9%9D%A2-%E5%8F%B0%E5%A1%91%E9%81%AE%E8%94%BD%E9%98%B2%E5%A1%B5%E8%86%A0%E5%B8%B6.webp','sales','2026-09-09T04:17:46.962Z');
CREATE TABLE timeline (     id INTEGER PRIMARY KEY AUTOINCREMENT,     year TEXT NOT NULL,     title TEXT NOT NULL,     description TEXT,     future_outlook TEXT , updated_by TEXT, updated_at TEXT);
INSERT INTO "timeline" ("id","year","title","description","future_outlook","updated_by","updated_at") VALUES(1,'1983','台塑塑膠加工組，於高雄前鎮廠起步','高雄前鎮廠開始生產購物袋，開啟塑膠袋製造歷程。','','admin','2026-09-10T07:16:58.341Z');
INSERT INTO "timeline" ("id","year","title","description","future_outlook","updated_by","updated_at") VALUES(2,'1984','耐熱袋、清潔袋加入產品線','高雄前鎮廠開始生產耐熱袋、清潔袋，產品線逐步擴展。','','admin','2026-09-10T07:17:29.672Z');
INSERT INTO "timeline" ("id","year","title","description","future_outlook","updated_by","updated_at") VALUES(3,'1989','新港廠整地擴建','建立後續聚乙烯薄膜與袋品生產基地。','',NULL,NULL);
INSERT INTO "timeline" ("id","year","title","description","future_outlook","updated_by","updated_at") VALUES(4,'1991','新港廠正式投產','啟用全自動拌料輸送系統，生產購物袋與清潔袋等產品。','',NULL,NULL);
INSERT INTO "timeline" ("id","year","title","description","future_outlook","updated_by","updated_at") VALUES(5,'1998','引進附拉繩清潔袋設備','由歐美引進新型設備，回應國內環保需求。','',NULL,NULL);
INSERT INTO "timeline" ("id","year","title","description","future_outlook","updated_by","updated_at") VALUES(6,replace('1990s\n–2000s','\n',char(10)),'跨海技術合作，建立長期默契','深化海外(美國)市場連結，累積跨國製造與品質管理經驗。','',NULL,NULL);
INSERT INTO "timeline" ("id","year","title","description","future_outlook","updated_by","updated_at") VALUES(7,'2004','高雄前鎮廠遷廠合併','整合生產線至新港廠，提升生產規模與效率。','',NULL,NULL);
INSERT INTO "timeline" ("id","year","title","description","future_outlook","updated_by","updated_at") VALUES(8,'2008','全球產品配置重整','優化全球供應鏈布局，強化產品線競爭力。','',NULL,NULL);
INSERT INTO "timeline" ("id","year","title","description","future_outlook","updated_by","updated_at") VALUES(9,'2014','台塑塑膠加工組改組，加入美國 INTEPLAST GROUP，臺灣營德股份有限公司正式成立','正式成立臺灣營德，融合台塑扎實根基與美國集團資源，邁向全新紀元。','',NULL,NULL);
INSERT INTO "timeline" ("id","year","title","description","future_outlook","updated_by","updated_at") VALUES(10,'2015','越南營德公司成立','拓展東南亞生產與服務據點，滿足全球客戶需求。','','admin','2026-09-10T07:19:22.706Z');
INSERT INTO "timeline" ("id","year","title","description","future_outlook","updated_by","updated_at") VALUES(12,'2020','開發醫療點滴袋外袋',replace('因應醫療用袋需求增加，完成點滴袋外袋開發。\n','\n',char(10)),'','admin','2026-09-10T07:21:08.731Z');
INSERT INTO "timeline" ("id","year","title","description","future_outlook","updated_by","updated_at") VALUES(13,'2026','把製造能力，推向下一個可能',replace('持續深化功能性薄膜、醫療包裝與永續產品，讓新港及越南基地以更靈活的技術與更穩定的品質，服務下一階段的市場需求。\n','\n',char(10)),'邁向 AI 智慧製造與全循環經濟，打造次世代綠色企業。',NULL,NULL);
CREATE TABLE synonyms (   id         INTEGER PRIMARY KEY AUTOINCREMENT,   product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,   say        TEXT NOT NULL, updated_by TEXT, updated_at TEXT,   UNIQUE (product_id, say) );
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(1,3,'垃圾袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(2,3,'垃圾桶袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(3,3,'廚餘袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(4,3,'大型垃圾袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(5,3,'環保袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(6,3,'塑膠袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(7,3,'trash bag',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(8,3,'garbage bag',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(9,3,'bin liner',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(10,3,'can liner',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(11,4,'束口袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(12,4,'抽繩袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(13,4,'穿繩袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(14,4,'drawstring',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(15,4,'draw tape',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(16,6,'密封袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(17,6,'封口袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(18,6,'拉鍊袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(19,6,'自封袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(20,6,'收納袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(21,6,'保鮮袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(22,6,'ziplock',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(23,6,'zip lock',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(24,6,'zipper',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(25,6,'freezer',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(26,2,'市場袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(27,2,'生鮮袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(28,2,'食物袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(29,2,'手扒雞袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(30,2,'微波袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(31,2,'塑膠袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(32,2,'produce',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(33,5,'塑膠手套',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(34,5,'拋棄式手套',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(35,5,'一次性手套',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(36,5,'glove',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(37,7,'養生膠帶',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(38,7,'防塵膜',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(39,7,'遮蔽膠帶',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(40,7,'油漆膠帶',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(41,7,'裝潢膠帶',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(42,7,'masking',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(43,7,'tape',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(44,1,'秤重紙',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(45,1,'墊紙',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(46,1,'包裝紙',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(55,1,'包裝秤重紙',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(56,1,'抽取式秤重紙',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(57,1,'秤紙',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(58,1,'tare sheet',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(59,1,'scale paper',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(60,1,'weighing paper',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(61,1,'weight sheet',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(63,1,'取用紙',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(64,1,'抽取式包裝紙',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(66,1,'抽取紙',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(68,1,'秤重膜',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(70,1,'稱重紙',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(72,1,'衛生秤重紙',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(74,1,'衛生紙卷',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(76,1,'防沾黏紙',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(77,2,'grocery bags',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(78,2,'果蔬袋',NULL,NULL);
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(79,2,'霧袋','admin','2026-09-10T00:44:29.479Z');
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(80,2,'點斷袋','admin','2026-09-10T00:44:44.156Z');
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(81,2,'ロールポリ','admin','2026-09-10T06:13:21.075Z');
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(82,2,'ポリロール','admin','2026-09-10T06:13:34.762Z');
INSERT INTO "synonyms" ("id","product_id","say","updated_by","updated_at") VALUES(83,2,'ミシン目ロール','admin','2026-09-10T06:13:44.273Z');
CREATE TABLE languages (   code       TEXT PRIMARY KEY,    label      TEXT NOT NULL,   is_base    INTEGER NOT NULL DEFAULT 0,     sort_order INTEGER NOT NULL DEFAULT 0 );
INSERT INTO "languages" ("code","label","is_base","sort_order") VALUES('zh-TW','繁體中文',1,0);
INSERT INTO "languages" ("code","label","is_base","sort_order") VALUES('en','English',0,1);
INSERT INTO "languages" ("code","label","is_base","sort_order") VALUES('ja','日本語',0,2);
CREATE TABLE translations (   id        INTEGER PRIMARY KEY AUTOINCREMENT,   entity    TEXT NOT NULL,          entity_id INTEGER NOT NULL,       field     TEXT NOT NULL,                    lang      TEXT NOT NULL REFERENCES languages(code) ON DELETE CASCADE,   value     TEXT NOT NULL DEFAULT '',   UNIQUE (entity, entity_id, field, lang) );
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(1,'setting',2,'value','en','6F., No. 205, Dunhua N. Rd., Songshan Dist., Taipei City, Taiwan');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(2,'setting',1,'value','en','INTEPLAST TAIWAN CORPORATION');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(3,'product',1,'name','en','Scale Sheet (Tare Sheet)');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(4,'product',2,'name','en','Produce Bags');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(5,'product',3,'name','en','Garbage Bags');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(6,'product',4,'name','en','Draw Tape Liners');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(7,'product',5,'name','en','Multifunctional Gloves');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(8,'product',6,'name','en','Zipper Bag');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(9,'product',7,'name','en','Pre-Taped Masking Film');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(10,'product',1,'highlight','en','Patented Single-Sheet Dispensing | Easy to Use, Reduced Contamination, Improved Hygiene');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(11,'product',2,'highlight','en','Food-grade safe materials｜Protecting freshness and hygiene of ingredients');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(12,'product',3,'highlight','en','Puncture-resistant, leak-proof, built for everyday waste');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(13,'product',4,'highlight','en','One pull closes the bag, with 30% more capacity and no mess on your hands');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(14,'product',5,'highlight','en','Skin-friendly comfort with clean, reliable protection');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(15,'product',6,'highlight','en','Solid grip・Air-tight seal, locking in freshness and cleanliness');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(16,'product',7,'highlight','en','A time-saver for renovation work and everyday dust protection');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(17,'product',1,'desc','en','Featuring the Group’s patented pull-out technology, Scale Sheet offers a smarter and more convenient alternative to traditional dispensing methods. Its easy-to-use single-sheet dispensing design allows for quick and efficient access, helping save valuable operation time while providing better control over material usage and costs. Durable, non-stick, and resistant to contamination, Scale Sheet is ideal for fresh food weighing, food preparation, industrial packaging, and retail counter operations, making it a professional choice for businesses seeking greater efficiency, hygiene, and convenience.');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(18,'product',2,'desc','en',replace('A premium produce bag range for fresh food and everyday retail. Made from certified food-grade resin that is safe, odourless and highly tear-resistant. Available flat-packed or on the roll, with heat-resistant bags, double-sealed food bags and market bags to choose from, locking in moisture and freshness so shoppers and store owners can rely on every layer of food safety.\n','\n',char(10)));
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(19,'product',3,'desc','en','Produced in-house from premium Formosa Plastics resin, using automated precision extrusion and sealing at our Xingang plant in Chiayi. The range covers perforated rolls, single-sheet dispensing and Green Mark certified liners. High tensile strength and load capacity handle both household waste and the high turnover of office buildings, restaurants and hotels without splitting or leaking.');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(20,'product',4,'desc','en','Designed for convenience and fast clean-up. The one-piece draw tape closes the bag with a single pull, so waste stays inside and hands stay clean. The construction adds over 30% usable capacity while sealing odours in. Medical-grade and eco draw-tape versions are also available, keeping homes and commercial premises visibly cleaner.');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(21,'product',5,'desc','en','A multi-purpose glove range combining high elasticity with a fine surface feel. The embossed inner texture makes them easy to put on and take off without sticking, while improving grip. Powder-free and latex-free throughout, they suit food preparation and processing, everyday cleaning and home care, staying flexible, comfortable and hygienic.');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(22,'product',6,'desc','en','A series of reusable zipper bags crafted with high standards. The bags are thick and provide a solid grip, paired with a dual-track or single-track zipper structure that offers excellent airtightness and moisture resistance. Whether for freezing and preserving fresh ingredients, organizing daily items, or packaging industrial parts, they provide superior sealing protection and can withstand multiple openings and closures while remaining tight.');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(23,'product',7,'desc','en','Masking tape and dust film in one. Made for interior decoration, spray painting, home renovation and medical disinfection screening, it covers large areas fast and protects furniture, floors and walls from dust and overspray. It adheres firmly and removes without residue, cutting masking preparation time while delivering complete protection.');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(24,'product',1,'items','en','Patent certificate');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(25,'product',2,'items','en','Heat-resistant bags, Double-sealed, Food bags, Market bags, Ice bags');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(26,'product',3,'items','en','Coreless roll, Interleaved, Can Liners, ECO Garbage Bag');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(27,'product',4,'items','en','Garbage Bags, Healthcare Isolation Bags, Eco draw tape');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(28,'product',5,'items','en','Powder-free, Latex-free, Embossed texture, Easy on/off, High elasticity, Soft feel');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(29,'product',6,'items','en','Zipper bags、Freezer bags、Zipper bags、Stand-up zipper bags (self-standing)');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(30,'product',7,'items','en','Masking protection, Disinfection screening, Dust cover, Fast application');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(31,'timeline',1,'title','en','Formosa Plastics processing group begins at Qianzhen');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(32,'timeline',2,'title','en','Produce and can liner bags added to the product line');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(33,'timeline',3,'title','en','Xingang Plant expansion begins');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(34,'timeline',4,'title','en','Xingang plant begins production');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(35,'timeline',5,'title','en','Draw-tape bag equipment introduced');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(36,'timeline',6,'title','en','Cross-sea technical cooperation and long-term synergy');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(37,'timeline',7,'title','en','Kaohsiung Qianzhen plant relocation and integration');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(38,'timeline',8,'title','en','Global product allocation restructuring');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(39,'timeline',9,'title','en','Formosa processing group reorganized, joined Inteplast Group, Taiwan Inteplast Corp. established');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(40,'timeline',10,'title','en','Vietnam Inteplast established');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(42,'timeline',12,'title','en','Development of medical IV bag outer packaging');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(43,'timeline',13,'title','en','Advancing manufacturing for what comes next');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(44,'timeline',1,'description','en','The Kaohsiung Qianzhen plant began producing shopping bags, starting its bag manufacturing history.');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(45,'timeline',2,'description','en','The Qianzhen plant began producing produce bags, gradually expanding the product line.');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(46,'timeline',3,'description','en','Foundation laid for polyethylene film and bag production.');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(47,'timeline',4,'description','en','An automated mixing and conveying system was introduced for shopping and refuse bag production.');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(48,'timeline',5,'description','en','New equipment was introduced from Europe and the United States to meet domestic environmental needs.');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(49,'timeline',6,'description','en','Deepened overseas market connections and accumulated cross-border manufacturing and quality management experience.');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(50,'timeline',7,'description','en','Integrated production lines into the Xingang plant to enhance operational scale and efficiency.');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(51,'timeline',8,'description','en','Optimized global supply chain layout and strengthened product line competitiveness.');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(52,'timeline',9,'description','en','Officially established Taiwan Inteplast Corporation, merging Formosa’s solid foundation with US group resources into a new era.');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(53,'timeline',10,'description','en','Expanded Southeast Asian production and service bases to meet localized customer demands overseas.');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(55,'timeline',12,'description','en',replace('In response to growing demand for medical packaging, developed IV overwrap bags.\n','\n',char(10)));
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(56,'timeline',13,'description','en',replace('We are advancing functional films, medical packaging, and sustainable products—bringing more agile technology and dependable quality to the market needs ahead.\n','\n',char(10)));
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(57,'setting',8,'value','en','Office hours: Mon–Fri 08:30–17:30 (GMT+8), closed on national holidays');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(63,'ui',6,'text','en','Yrs (1983-{{year}})');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(64,'ui',7,'text','en','{{years}} Years Group History');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(242,'product',1,'name','ja','スケールシート（重量測定シート）');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(243,'product',1,'highlight','ja','グループ特許の単枚取り出し設計｜便利な取り扱い・汚染しにくい・衛生的');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(244,'product',1,'desc','ja','グループの特許技術を組み込んだ、抽出式のスケールシートです。従来の取り扱い方法の煩雑さと不便さを打破しました。使いやすい単枚取り出し設計で、取り扱いが簡単で、操作も便利です。作業効率の向上、取り扱い時間の短縮、使用コストの有効なコントロールを実現します。材質は強靭で、汚染に強く、粘着しにくいため、生鮮食品の計量、飲食店での準備、工業製品の小分け、商業施設のカウンターなど、様々な作業現場で使用できます。高い効率性、衛生性、利便性を追求するプロフェッショナルのための最適な選択です。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(245,'product',1,'items','ja','特許証明書');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(246,'product',2,'name','ja','野菜・果物袋');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(247,'product',2,'highlight','ja','食品グレードの安心素材｜食材の鮮度と衛生を守る');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(248,'product',2,'desc','ja','生鮮食品や日常の小売りに最適な高品質な野菜・果物袋シリーズ。食品グレードの合格原料を厳選し、素材は安全で無毒・無味。優れた引張強度を備えている。平装・巻装など多様な規格を用意し、耐熱袋・ダブルシール食品袋・市場専用袋など多種多様な選択肢を提供。食材の水分と鮮度を効果的に保持し、消費者と商家の厳格な食品安全対策をサポート。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(249,'product',2,'items','ja','耐熱袋、ダブルシール、食品袋、市場袋、アイスバッグ');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(250,'product',3,'name','ja','クリーニングポリ袋');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(251,'product',3,'highlight','ja','強靭で耐刺傷性・水漏れしない日常クリーニングの必需品');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(252,'product',3,'desc','ja','台湾塑膠の高品質原料を活かした自社製造の強みを生かし、嘉義新港工場の自動化精密ブロー成形・シール技術で製造。全シリーズは、ロール式・単張り抽出式・国家環境保護マーク認定クリーニングポリ袋など、様々なスタイルをカバー。優れた引張強度と耐荷重性を備え、一般家庭の日常ゴミ収集からオフィスビル・飲食店・ホテルなどの高頻度業務用現場まで、軽々と対応でき、安心して使用できる。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(253,'product',3,'items','ja','ロール式、単張り抽出式、八つ折り袋、エコクリーニングポリ袋');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(254,'product',4,'name','ja','コード付きバッグ');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(255,'product',4,'highlight','ja','ワンプルで口を閉じ、容量が30％増加 ・ 手が汚れない');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(256,'product',4,'desc','ja','現代の利便性と効率的な清掃に特化した、貼り心地の良い商品。一体成型の丈夫なコード構造により、簡単な操作で口を閉じることができ、清掃時のゴミの漏れや手の汚れを効果的に防ぎます。特殊な設計により、内部空間の利用効率が30％以上向上し、においをしっかりと閉じ込めます。医療用とエココードのオプションもあり、家庭やオフィスの環境をより清潔で衛生的にします。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(257,'product',4,'items','ja','清掃袋、医療袋、エココード付きバッグ');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(258,'product',5,'name','ja','多機能手套');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(259,'product',5,'highlight','ja','肌膚に優しい快適さ｜保護機能に優れた万能プロテクション手套');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(260,'product',5,'desc','ja','優れた伸縮性と繊細な感触を兼ね備えた多機能手套シリーズ。表面には特殊な内圧紋設計を採用し、着脱がスムーズで、粘着しないだけでなく、優れた滑り止めグリップ力を発揮。全シリーズがパウダーフリー、ラテックスフリーなどの肌に優しい基準を満たしており、飲食店での調理、食品加工、日常の清掃やホームケアなど、幅広いシーンで快適な衛生保護体験を提供します。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(261,'product',5,'items','ja','パウダーフリー・ラテックスフリー・内圧紋・着脱容易・優れた伸縮性・良好な感触');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(262,'product',6,'name','ja','チャック袋');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(263,'product',6,'highlight','ja','しっかりとした手触り・密封性に優れ、鮮度と清潔さを完璧にキープ');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(264,'product',6,'desc','ja','高い水準の製造プロセスで作られた、繰り返し使えるチャック袋シリーズ。袋の本体は厚くてしっかりしており、密封性に優れたダブルトラックまたはシングルトラックのチャック構造を採用。優れた気密性と防湿性能を備えています。生鮮食品の冷凍保存、日常の小物の分類収納、工業部品の包装などに最適で、繰り返し開閉しても密封性が持続します。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(265,'product',6,'items','ja','保存袋、冷凍袋、チャック袋、自立チャック袋（スタンドタイプ）');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(266,'product',7,'name','ja','マスキングテープ');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(267,'product',7,'highlight','ja','施工・装飾や日常の防塵に最適な時短ツール');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(268,'product',7,'desc','ja','テープと防塵フィルムが一体化した便利な保護ソリューション。室内装飾・塗装・リフォーム・医療用消毒保護のために設計されており、家具・床・壁を粉塵や塗料の飛沫から素早く・広範囲に保護します。貼り付けがしっかりしており、はがしても残留物がなく、施工前の面倒な養生作業を大幅に簡素化し、高い効率と完璧な保護効果を実現します。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(269,'product',7,'items','ja','養生保護、消毒保護、粉塵被覆、施工便利');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(275,'ui',6,'text','ja','年 (1983-{{year}})');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(276,'ui',7,'text','ja','グローバルブランド {{years}} 年の実績');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(397,'ui',129,'text','ja','一つひとつの選択が、<br>グリーンな暮らしへ。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(402,'ui',134,'text','ja','地球を包む緑の葉が、<br>やさしい選択の目印に。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(456,'timeline',1,'title','ja','台塑のプラスチック加工チームが前鎮工場でスタート');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(457,'timeline',1,'description','ja','高雄前鎮工場でショッピングバッグの生産を開始し、袋製品の製造が始まった。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(458,'timeline',2,'title','ja','市場袋・清掃袋の製品ラインに新たに参入');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(459,'timeline',2,'description','ja','前鎮工場にて市場袋・清掃袋の生産を開始し、製品ラインを段階的に拡大しています。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(460,'timeline',3,'title','ja','新港工場の整地・拡張');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(461,'timeline',3,'description','ja','今後のポリエチレン・フィルムおよび袋製品の生産拠点の構築。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(462,'timeline',4,'title','ja','新港工場が正式に稼働開始');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(463,'timeline',4,'description','ja','全自動混合材輸送システムを導入。ショッピングバッグ・クリーニング袋などの製品を製造。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(464,'timeline',5,'title','ja','コード付きクリーニングバッグ装置を導入');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(465,'timeline',5,'description','ja','欧米から新型装置を導入し、国内の環境保護ニーズに応えます。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(466,'timeline',6,'title','ja','越海技術協力で長期的な信頼関係を構築');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(467,'timeline',6,'description','ja','海外市場の接続を深め、国を越えた製造と品質管理の経験を蓄積します。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(468,'timeline',7,'title','ja','高雄前鎮工場移転・統合');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(469,'timeline',7,'description','ja','生産ラインを新港工場に統合し、生産規模と効率を向上。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(470,'timeline',8,'title','ja','グローバル製品構成の再編');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(471,'timeline',8,'description','ja','グローバルサプライチェーンの最適化を図り、製品ラインの競争力を強化します。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(472,'timeline',9,'title','ja','台湾の台塑グループが改組し、米国のINTEPLAST GROUPが参加、台湾営徳株式会社が正式に設立');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(473,'timeline',9,'description','ja','台湾営徳株式会社が正式に設立され、台塑の確固たる基盤と米国のグループリソースを融合し、新たな時代に突入。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(474,'timeline',10,'title','ja','ベトナム営德社の設立');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(475,'timeline',10,'description','ja','東南アジアでの生産とサービス拠点を拡大し、海外顧客のローカルニーズに応える。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(478,'timeline',12,'title','ja','医療用輸液バッグの開発');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(479,'timeline',12,'description','ja','医療用包装分野に進出。厳格な品質管理により業界から信頼を得ています。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(480,'timeline',13,'title','ja','製造能力の新たな可能性へ');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(481,'timeline',13,'description','ja','デジタルトランスフォーメーション、AI スマート製造、持続可能なエコパッケージングを深化させ、業界の未来をリードします。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(482,'timeline',13,'future_outlook','ja','AI スマート製造とサーキュラーエコノミーへの移行を目指し、次世代のグリーン企業を構築します。');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(483,'timeline',13,'future_outlook','en','Embracing AI smart manufacturing and circular economy, building a next-generation green enterprise.');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(492,'ui',129,'text','en','Every choice you make,<br>a step closer to green living.');
INSERT INTO "translations" ("id","entity","entity_id","field","lang","value") VALUES(494,'ui',134,'text','en','Green leaves around the Earth,<br>the mark of a kinder choice.');
CREATE TABLE settings (   id           INTEGER PRIMARY KEY AUTOINCREMENT,   key          TEXT NOT NULL UNIQUE,   value        TEXT NOT NULL DEFAULT '',   label        TEXT NOT NULL DEFAULT '',    hint         TEXT NOT NULL DEFAULT '',   translatable INTEGER NOT NULL DEFAULT 0,   sort_order   INTEGER NOT NULL DEFAULT 0 , updated_by TEXT, updated_at TEXT);
INSERT INTO "settings" ("id","key","value","label","hint","translatable","sort_order","updated_by","updated_at") VALUES(1,'company_name','臺灣營德股份有限公司','公司名稱','',1,1,NULL,NULL);
INSERT INTO "settings" ("id","key","value","label","hint","translatable","sort_order","updated_by","updated_at") VALUES(2,'address','臺北市松山區敦化北路205號6樓609室','公司地址','各語言可以有自己的寫法',1,2,NULL,NULL);
INSERT INTO "settings" ("id","key","value","label","hint","translatable","sort_order","updated_by","updated_at") VALUES(3,'phone','02-2712-2211 #8109','總機電話（顯示用）','例：02-2712-2211 #8109',0,3,NULL,NULL);
INSERT INTO "settings" ("id","key","value","label","hint","translatable","sort_order","updated_by","updated_at") VALUES(4,'phone_link','0227122211,8109','總機電話（撥號用）','只留數字與逗號',0,4,NULL,NULL);
INSERT INTO "settings" ("id","key","value","label","hint","translatable","sort_order","updated_by","updated_at") VALUES(5,'email','inteplasttw@fpc.com.tw','聯絡信箱','詢價通知會寄到這裡',0,5,'admin','2026-09-10T07:34:24.991Z');
INSERT INTO "settings" ("id","key","value","label","hint","translatable","sort_order","updated_by","updated_at") VALUES(6,'email_cc','','副本收件人','可留空',0,6,NULL,NULL);
INSERT INTO "settings" ("id","key","value","label","hint","translatable","sort_order","updated_by","updated_at") VALUES(7,'copyright','© 2026 INTEPLAST TAIWAN CORPORATION. All Rights Reserved.','頁尾版權文字','',1,7,NULL,NULL);
INSERT INTO "settings" ("id","key","value","label","hint","translatable","sort_order","updated_by","updated_at") VALUES(8,'office_hours','服務時間：週一至週五 08:30–17:30（國定假日休息）','服務時間','顯示在聯繫我們的電話下方。客戶看到號碼的當下就知道現在打有沒有人接',1,8,NULL,NULL);
CREATE TABLE synonym_suggestions (   id         INTEGER PRIMARY KEY AUTOINCREMENT,   product_id INTEGER NOT NULL,   say        TEXT NOT NULL,   source     TEXT NOT NULL DEFAULT 'ai',   status     TEXT NOT NULL DEFAULT 'pending',   created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,   UNIQUE (product_id, say) );
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(9,1,'抽取式秤重紙','ai','approved','2026-09-07 00:30:14');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(10,1,'衛生秤重紙','ai','approved','2026-09-07 00:30:14');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(11,1,'秤紙','ai','approved','2026-09-07 00:30:14');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(12,1,'取用紙','ai','approved','2026-09-07 00:30:14');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(13,1,'防沾黏紙','ai','approved','2026-09-07 00:30:14');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(14,1,'抽取式包裝紙','ai','approved','2026-09-07 00:30:14');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(15,1,'稱重紙','ai','approved','2026-09-07 00:30:14');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(16,1,'秤重膜','ai','approved','2026-09-07 00:30:14');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(17,1,'包裝秤重紙','ai','approved','2026-09-07 00:30:14');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(18,1,'抽取紙','ai','approved','2026-09-07 00:37:15');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(19,1,'衛生紙卷','ai','approved','2026-09-07 00:37:15');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(21,1,'tare sheet','ai','approved','2026-09-07 00:37:15');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(22,1,'weight sheet','ai','approved','2026-09-07 00:37:15');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(23,1,'scale paper','ai','approved','2026-09-07 00:37:15');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(24,1,'weighing paper','ai','approved','2026-09-07 00:37:15');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(25,2,'蔬果包裝袋','ai','rejected','2026-09-07 07:07:09');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(26,2,'食品包裝袋','ai','rejected','2026-09-07 07:07:09');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(27,2,'果蔬袋','ai','approved','2026-09-07 07:07:09');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(28,2,'買い物袋','ai','rejected','2026-09-07 07:07:09');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(29,2,'食料品袋','ai','rejected','2026-09-07 07:07:09');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(30,2,'grocery bags','ai','approved','2026-09-07 07:07:09');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(31,2,'野菜袋','ai','rejected','2026-09-07 07:07:09');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(32,2,'果物包装袋','ai','rejected','2026-09-07 07:07:09');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(33,3,'waste bag','ai','pending','2026-09-08 12:29:36');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(34,3,'plastic bag','ai','pending','2026-09-08 12:29:36');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(35,3,'ゴミ袋','ai','pending','2026-09-08 12:29:36');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(36,3,'プラスチック袋','ai','pending','2026-09-08 12:29:36');
INSERT INTO "synonym_suggestions" ("id","product_id","say","source","status","created_at") VALUES(37,3,'ポリ袋','ai','pending','2026-09-08 12:29:36');
CREATE TABLE inquiries (   id         INTEGER PRIMARY KEY AUTOINCREMENT,   company    TEXT NOT NULL DEFAULT '',   email      TEXT NOT NULL DEFAULT '',   phone      TEXT NOT NULL DEFAULT '',   product    TEXT NOT NULL DEFAULT '',   message    TEXT NOT NULL DEFAULT '',   lang       TEXT NOT NULL DEFAULT '',   page       TEXT NOT NULL DEFAULT '',   status     TEXT NOT NULL DEFAULT 'new',   note       TEXT NOT NULL DEFAULT '',   created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP , updated_by TEXT, updated_at TEXT);
INSERT INTO "inquiries" ("id","company","email","phone","product","message","lang","page","status","note","created_at","updated_by","updated_at") VALUES(1,'個人','lyanchen@wpjk.inteplast.com','3612504539','清潔袋 (連捲 / 單張抽取 / 環保)','0','zh-TW','/contact','new','','2026-09-07 01:57:39',NULL,NULL);
CREATE TABLE ui_strings (   id    INTEGER PRIMARY KEY AUTOINCREMENT,   zh    TEXT NOT NULL UNIQUE,             page  TEXT NOT NULL DEFAULT '',         note  TEXT NOT NULL DEFAULT '' , hidden INTEGER NOT NULL DEFAULT 0, zh_key TEXT, updated_by TEXT, updated_at TEXT);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(1,'臺灣營德股份有限公司 | INTEPLAST TAIWAN CORPORATION','首頁','',0,'臺灣營德股份有限公司 | INTEPLAST TAIWAN CORPORATION',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(2,'臺灣營德股份有限公司 (INTEPLAST TAIWAN CORPORATION) 為台塑關係企業與 INTEPLAST USA 合資大廠，專業生產清潔袋、拉繩袋、蔬果袋、夾鏈袋、手套/遮蔽膠帶與 Scale Sheet，提供多元日常與工業應用情境。','首頁','',0,'臺灣營德股份有限公司 (INTEPLAST TAIWAN CORPORATION) 為台塑關係企業與 INTEPLAST USA 合資大廠，專業生產清潔袋、拉繩袋、蔬果袋、夾鏈袋、手套/遮蔽膠帶與 Scale Sheet，提供多元日常與工業應用情境。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(3,'台塑品牌塑膠袋專業製造','首頁','',0,'台塑企業清潔袋專業製造','admin','2026-09-10T06:19:52.359Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(4,'台塑企業、INTEPLAST USA 與長庚生技合資建立公司。以台塑品牌自製清潔袋與拉繩清潔袋，嘉義新港、越南工廠自動化生產；另有耐熱袋、夾鏈袋，以及專利抽取式 Scale Sheet。','首頁','',0,'台塑企業、INTEPLAST USA 與長庚生技合資建立公司。以台塑原料自製清潔袋與拉繩袋，嘉義新港、越南基地自動化吹膜；另有蔬果袋、夾鏈袋，以及集團專利抽取式 Scale Sheet。','admin','2026-09-10T06:24:01.250Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(5,'瀏覽核心產品系列','首頁','',0,'瀏覽核心產品系列',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(6,'年 (1983-{{year}})','首頁','',1,'年 (1983-{{year}})',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(7,'{{years}} 年全球品牌資歷','首頁','',1,'{{years}} 年全球品牌資歷',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(8,'1983 建廠 · 2014 在臺設立臺灣營德股份有限公司','首頁','',0,'INTEPLAST USA 1983 創立 · 2014 在台建立公司','admin','2026-09-10T06:27:24.732Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(9,'品質管理系統認證','首頁','',0,'品質管理系統認證',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(10,'ISO 9001:2015 嚴格把關','首頁','',0,'ISO 9001:2015 嚴格把關',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(11,'廠內廢料閉環乾淨回收','首頁','',0,'廠內廢料閉環回收','admin','2026-09-10T06:30:58.090Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(12,'100% 邊角料粉碎造粒','首頁','',0,'100% 邊角料即時粉碎造粒','admin','2026-09-10T06:30:05.732Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(13,'CORE PRODUCTS · 核心產品系列','首頁','',0,'CORE PRODUCTS · 核心產品系列',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(14,'核心產品系列','首頁','',0,'核心產品系列',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(15,'嘉義新港工廠一貫作業，從家用清潔袋到專利 Scale Sheet。','首頁','',0,'全線產品皆以台塑原料自製，嘉義新港基地一貫作業，從家用清潔袋到集團專利 Scale Sheet。','admin','2026-09-10T06:33:54.920Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(16,'ENVIRONMENTAL LABEL PRODUCTS · 綠色標章產品','首頁','',0,'ENVIRONMENTAL LABEL PRODUCTS · 綠色標章產品',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(17,'環保不打折，每一款都經過層層把關','首頁','',0,'環保不打折，每一款都經過層層把關',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(18,'台塑環保拉繩清潔袋與台塑環保清潔袋，皆通過環保標章審查並取得使用證書；從原料到製程，將友善環境落實於日常使用。','首頁','',0,'台塑環保拉繩清潔袋與台塑環保清潔袋，皆通過環保標章審查並取得使用證書；從原料到製程，將環境考量落實於日常使用。','admin','2026-09-10T06:51:53.140Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(19,'環保標章認證產品','首頁','',0,'環保標章認證產品',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(20,'通過製程及環境審查','首頁','',0,'通過環境審查','admin','2026-09-10T06:54:21.308Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(21,'符合環保標章規格標準，取得產品標示資格。','首頁','',0,'符合環保標章規格標準，取得產品標示資格。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(22,'50% 以上再生塑膠','首頁','',0,'50% 再生塑膠','admin','2026-09-10T06:55:18.593Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(23,'塑膠資源循環利用，延續材料價值。','首頁','',0,'減少對原生塑膠資源的依賴，延續材料價值。','admin','2026-09-10T06:57:24.317Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(24,'避用重金屬','首頁','',0,'避用重金屬',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(25,'不使用鉛、鎘、汞及六價鉻等重金屬。','首頁','',0,'不使用鉛、鎘、汞及六價鉻等重金屬。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(26,'製程審慎管理','首頁','',0,'製程審慎管理',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(27,'避用列管毒性化學物質及相關管制物。','首頁','',0,'避用列管毒性化學物質及相關管制物。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(28,'查看更多','首頁','',0,'查看更多',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(29,'留下聯絡資料，我們將由專人與您聯繫','首頁','',0,'留下聯絡資料，我們將由專人與您聯繫',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(30,'無論是產品規格諮詢或客製化需求，歡迎留下資訊，我們將有專人與您對接。','首頁','',0,'無論是產品規格諮詢、外銷配合或客製化需求，歡迎留下資訊，我們將有專人與您對接。','admin','2026-09-10T07:00:47.907Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(31,'留下聯絡資料','首頁','',0,'留下聯絡資料',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(32,'清潔袋 · 拉繩袋 · 蔬果袋...','首頁','',0,'清潔袋 · 拉繩袋 · 蔬果袋...',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(33,'綠色標章認證','首頁','',0,'綠色標章認證',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(34,'50% 再生塑膠 · 避用重金屬','首頁','',0,'50% 再生塑膠 · 避用重金屬',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(35,'聯繫專人窗口','首頁','',0,'聯繫專人窗口',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(36,'留下資料 · 由專人與您對接','首頁','',0,'留下資料 · 由專人與您對接',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(37,'快速篩選：','首頁','',0,'快速篩選：',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(42,'前往產品中心查看','首頁','',0,'前往產品中心查看',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(43,'認識臺灣營德股份有限公司：從台塑嘉義新港廠到 INTEPLAST GROUP 全球製造網絡，超過三十年的塑膠薄膜、清潔袋與軟包裝製造歷程。','關於營德','',0,'認識臺灣營德股份有限公司：從台塑新港廠到 INTEPLAST GROUP 全球製造網絡，超過三十年的塑膠薄膜、清潔袋與軟包裝製造歷程。','admin','2026-09-10T08:30:28.438Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(44,'關於臺灣營德｜從新港出發的全球製造實力','關於營德','',0,'關於臺灣營德｜從新港出發的全球製造實力',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(45,'從台灣出發，為世界製造','關於營德','',0,'從台灣出發，為世界製造',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(46,'在嘉義新港，我們把穩定品質、精密製程與環境思維，做成全球市場可以信賴的產品。臺灣營德持續用更好的製造，回應每一個正在前進的需求。','關於營德','',0,'在新港，我們把穩定品質、精密製程與環境思維，做成全球市場可以信賴的日常。臺灣營德持續用更好的製造，回應每一個正在前進的需求。','admin','2026-09-10T07:04:13.845Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(47,'整合全球技術與在地根基，讓製造更有韌性','關於營德','',0,'整合全球技術與在地根基，讓製造更有韌性',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(48,'臺灣營德站在嘉義新港，串連 INTEPLAST GROUP 的全球加工經驗與台塑公司的原料、廠區資源；把三方力量，轉化為客戶可依賴的製造能力。','關於營德','',0,'臺灣營德站在新港，串連 INTEPLAST GROUP 的全球加工經驗與台塑公司的原料、廠區資源；把三方力量，轉化為客戶可依賴的製造能力。','admin','2026-09-10T08:30:28.397Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(49,'全球塑膠加工技術、製造管理與跨市場服務網絡。','關於營德','',0,'全球塑膠加工技術、製造管理與跨市場服務網絡。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(50,'美國總部｜北美、亞洲、歐洲製造版圖','關於營德','',0,'美國總部｜北美、亞洲、歐洲製造版圖',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(51,'前往 INTEPLAST GROUP 官網','關於營德','',0,'前往 INTEPLAST GROUP 官網',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(52,'臺灣營德股份有限公司','關於營德','',0,'臺灣營德','admin','2026-09-10T07:08:40.284Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(53,'在嘉義新港，把原料、技術與製程整合為穩定可靠的薄膜與軟包裝解決方案。','關於營德','',0,'在嘉義新港，把原料、技術與製程整合為穩定可靠的薄膜與軟包裝解決方案。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(54,'共同投資夥伴：INTEPLAST GROUP、台灣塑膠工業股份有限公司、長庚生物科技','關於營德','',0,'共同投資夥伴：INTEPLAST GROUP、台灣塑膠公司、長庚生物科技','admin','2026-09-10T08:25:48.108Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(55,'與臺灣營德聯繫','關於營德','',0,'與臺灣營德聯繫',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(56,'台灣塑膠工業股份有限公司','關於營德','',0,'台灣塑膠公司','admin','2026-09-10T08:25:48.100Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(57,'穩定的原料資源與台塑企業嘉義新港廠區產業基礎，支撐高效率且穩定的生產配置。','關於營德','',0,'穩定的原料資源與台塑企業新港廠區產業基礎，支撐高效率且穩定的生產配置。','admin','2026-09-10T08:30:28.412Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(58,'台灣塑膠工業股份有限公司｜台塑企業成員','關於營德','',0,'台灣塑膠公司｜台塑企業成員','admin','2026-09-10T08:25:48.112Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(59,'前往台灣塑膠工業股份有限公司官網','關於營德','',0,'前往台灣塑膠公司官網','admin','2026-09-10T08:25:48.082Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(60,'三方共同投資，讓臺灣營德兼具國際製造視野、在地供應韌性與長期經營基礎。','關於營德','',0,'三方共同投資，讓臺灣營德兼具國際製造視野、在地供應韌性與長期經營基礎。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(61,'從台塑到營德，厚植製造實力','關於營德','',0,'從台塑到營德，厚植製造實力',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(62,'臺灣營德的製造故事，源自台塑塑膠加工組。1983 年，加工組於高雄前鎮廠起步，開始生產購物袋；1984 年，市場袋、清潔袋正式加入產品線，逐步累積袋品製造的基礎與經驗。','關於營德','',0,'臺灣營德的製造故事，源自台塑塑膠加工組。1983 年，加工組於高雄前鎮廠起步，開始生產購物袋；1984 年，市場袋、清潔袋正式加入產品線，逐步累積袋品製造的基礎與經驗。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(63,'1989 年，嘉義新港廠整地擴建；1991 年正式投產，並啟用全自動拌料輸送系統。隨著市場需求與設備能力提升，產品線也持續延伸。','關於營德','',0,'1989 年，新港廠整地擴建；1991 年正式投產，並啟用全自動拌料輸送系統。隨著市場需求與設備能力提升，產品線也持續延伸。','admin','2026-09-10T08:30:28.415Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(64,'2004 年，高雄前鎮廠遷廠合併，新港成為主要生產基地；2008 年，全球產品配置重整，讓製造資源更聚焦於具技術與品質優勢的產品。','關於營德','',0,'2004 年，前鎮廠遷廠合併，新港成為主要生產基地；2008 年，全球產品配置重整，讓製造資源更聚焦於具技術與品質優勢的產品。','admin','2026-09-10T08:29:17.295Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(65,'2014 年，台塑塑膠加工組改組，成立「臺灣營德股份有限公司」。臺灣營德延續既有的製造經驗，結合 INTEPLAST GROUP 的全球技術與營運管理，並持續作為台塑相關企業的一員，開啟新的篇章。','關於營德','',0,'2014 年，台塑塑膠加工組改組，成立「臺灣營德股份有限公司」。臺灣營德延續既有的製造經驗，結合 INTEPLAST GROUP 的全球技術與營運管理，並持續作為台塑相關企業的一員，開啟新的篇章。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(66,'2015 年，越南營德公司成立，進一步拓展海外製造布局。透過臺灣與越南生產基地的相互支援，結合 INTEPLAST GROUP 的全球資源與技術經驗，逐步強化產能配置與國際市場供應能力。','關於營德','',0,'2015 年，越南營德公司成立，進一步拓展海外製造布局。透過臺灣與越南生產基地的相互支援，結合 INTEPLAST GROUP 的全球資源與技術經驗，逐步強化產能配置與國際市場供應能力。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(67,'從高雄前鎮到嘉義新港的持續精進；我們把累積多年的製造經驗，轉化為面向未來的可靠承諾。','關於營德','',0,'從前鎮的第一只購物袋，到新港的持續精進；我們把累積多年的製造經驗，轉化為面向未來的可靠承諾。','admin','2026-09-10T08:29:17.303Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(68,'臺灣營德的製造歷程','關於營德','',0,'臺灣營德的製造歷程',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(69,'故事始於高雄前鎮廠，從袋品生產出發，逐步發展為今日的製造基地。','關於營德','',0,'故事始於高雄前鎮廠，從袋品生產出發，逐步發展為今日的製造基地。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(70,'集團肯定，來自實際的生產表現','關於營德','',0,'集團肯定，來自實際的生產表現',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(71,'臺灣營德連續五年獲頒 INTEPLAST GROUP Excellence Award 卓越獎。','關於營德','',0,'臺灣營德連續五年獲頒 INTEPLAST GROUP Excellence Award 卓越獎。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(72,'INTEPLAST GROUP 卓越獎與年度最大進步營運單位獎座','關於營德','',0,'INTEPLAST GROUP 卓越獎與年度最大進步營運單位獎座',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(73,'抽取式設計，取得美國專利','關於營德','',0,'抽取式設計，取得美國專利',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(74,'Scale Sheet 的單張抽取結構已取得美國專利。取用一張就是一張，不必翻找、不會沾黏，讓秤重與分裝的每一次動作都衛生乾淨、省下時間。','關於營德','',0,'Scale Sheet 的單張抽取結構已取得美國專利。取用一張就是一張，不必翻找、不會沾黏，讓秤重與分裝的每一次動作都省下時間。','admin','2026-09-10T07:24:00.141Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(75,'不只是製造，更是對品質與未來的承諾','關於營德','',0,'不只是製造，更是對品質與未來的承諾',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(76,'從自動化生產、跨市場產品開發到循環再利用，我們把三十餘年的現場經驗轉化為客戶可以信賴的製造能力。','關於營德','',0,'從自動化生產、跨市場產品開發到循環再利用，我們把三十餘年的現場經驗轉化為客戶可以信賴的製造能力。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(77,'讓穩定品質，成為製程的日常','關於營德','',0,'讓穩定品質，成為製程的日常',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(78,'從全自動拌料與原料空輸，從吹膜控制與精密點斷熱封，每一道製程都為穩定品質與良率而設計。','關於營德','',0,'從全自動拌料與原料空輸，到 PLC 吹膜控制與精密點斷熱封，每一道製程都為穩定品質與良率而設計。','admin','2026-09-10T07:24:57.037Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(79,'製程 × 品質管理','關於營德','',0,'製程 × 品質管理',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(80,'以多元產品，回應全球市場','關於營德','',0,'以多元產品，回應全球市場',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(81,'從包裝膜、清潔袋、拉繩清潔袋、醫療包裝袋、冷凍袋、密實袋，臺灣營德服務台灣、日本、美洲、澳洲與東南亞等市場。','關於營德','',0,'從捲膜、清潔袋、拉繩袋到醫療包裝與冷凍密實袋，臺灣營德服務台灣、日本、美洲與東南亞等市場。','admin','2026-09-10T07:27:41.372Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(82,'產品 × 市場連結','關於營德','',0,'產品 × 市場連結',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(83,'把永續，落實在每個細節','關於營德','',0,'把永續，落實在每個細節',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(84,'採用環保水性墨、建構廢膜回收再生系統，並推出取得國家環保標章認證的綠色產品。','關於營德','',0,'採用環保水性墨、建構廢膜回收再生系統，並推出取得國家環保標章認證的綠色產品。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(85,'材料 × 循環思維','關於營德','',0,'材料 × 循環思維',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(86,'把現場經驗，轉化成每一批產品的可靠度','關於營德','',0,'把現場經驗，轉化成每一批產品的可靠度',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(87,'嘉義新港工廠將原料輸送、吹膜、印刷、製袋與品質控管串聯為完整流程，讓品質不是最後一道檢查，而是每一道製程的共同標準。','關於營德','',0,'新港基地將原料輸送、吹膜、印刷、製袋與品質控管串聯為完整流程，讓品質不是最後一道檢查，而是每一道製程的共同標準。','admin','2026-09-10T07:28:36.020Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(88,'全自動拌料與原料空輸','關於營德','',0,'全自動拌料與原料空輸',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(89,'自動化吹膜控制','關於營德','',0,'PLC 自動化吹膜控制','admin','2026-09-10T07:29:12.556Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(90,'精密點斷、熱封與品質追蹤','關於營德','',0,'精密點斷、熱封與品質追蹤',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(91,'下一段製造故事，與您一起開始','關於營德','',0,'下一段製造故事，與您一起開始',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(92,'需要穩定可靠的塑膠薄膜、袋品或軟包裝製造夥伴？讓臺灣營德的技術與全球網絡，回應您的產品需求。','關於營德','',0,'需要穩定可靠的塑膠薄膜、袋品或軟包裝製造夥伴？讓臺灣營德的技術與全球網絡，回應您的產品需求。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(93,'聯繫與詢價','關於營德','',0,'聯繫與詢價',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(94,'瀏覽產品中心','關於營德','',0,'瀏覽產品中心',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(95,'聯繫我們 | 臺灣營德股份有限公司 INTEPLAST TAIWAN CORPORATION','聯繫我們','',0,'聯繫我們 | 臺灣營德股份有限公司 INTEPLAST TAIWAN CORPORATION',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(96,'聯繫臺灣營德股份有限公司 (INTEPLAST TAIWAN) 外銷業務團隊。地址：臺北市松山區敦化北路205號6樓609室，電話：02-2712-2211 #8109。','聯繫我們','',0,'聯繫臺灣營德股份有限公司 (INTEPLAST TAIWAN) 外銷業務團隊。地址：臺北市松山區敦化北路205號6樓609室，電話：02-2712-2211 #8109。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(97,'聯繫臺灣營德','聯繫我們','',0,'聯繫臺灣營德',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(98,'留下聯絡資料由我們主動與您聯繫，或直接聯絡營德專人窗口。','聯繫我們','',0,'留下聯絡資料由我們主動與您聯繫，或直接聯絡營德專人窗口。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(99,'直接聯繫營德窗口','聯繫我們','',0,'直接聯繫營德窗口',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(100,'留下資料 · 由我們聯繫您','聯繫我們','',0,'留下資料 · 由我們聯繫您',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(101,'聯絡我們','聯繫我們','',0,'聯絡我們',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(102,'公司地址','聯繫我們','',0,'公司地址',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(103,'臺北市松山區敦化北路205號6樓609室','聯繫我們','',0,'臺北市松山區敦化北路205號6樓609室',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(104,'連絡電話','聯繫我們','',0,'連絡電話',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(105,'服務時間：週一至週五 08:00–17:00（國定假日休息）','聯繫我們','',0,'服務時間：週一至週五 08:30–17:30（國定假日休息）','admin','2026-09-10T07:02:25.905Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(106,'電子郵件','聯繫我們','',0,'電子郵件',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(107,'撥打電話','聯繫我們','',0,'撥打電話',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(108,'寄送 Email 諮詢','聯繫我們','',0,'寄送 Email 諮詢',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(109,'留下您的聯絡資料','聯繫我們','',0,'留下您的聯絡資料',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(110,'公司名稱','聯繫我們','',0,'公司名稱',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(111,'例：Global Packaging Co., Ltd.','聯繫我們','',0,'例：Global Packaging Co., Ltd.',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(112,'商務信箱（必填）','聯繫我們','',0,'商務信箱（必填）',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(113,'name@yourcompany.com','聯繫我們','',0,'name@yourcompany.com',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(114,'聯絡電話（選填）','聯繫我們','',0,'聯絡電話（選填）',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(115,'例：02-2712-2211 或 0912-345-678','聯繫我們','',0,'例：02-2712-2211 或 0912-345-678',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(116,'詢問產品類別','聯繫我們','',0,'詢問產品類別',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(117,'01 清潔袋 (連捲 / 單張抽取 / 環保)','聯繫我們','',0,'01 清潔袋 (連捲 / 單張抽取 / 環保)',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(118,'02 拉繩袋 (清潔袋 / 醫療袋)','聯繫我們','',0,'02 拉繩袋 (清潔袋 / 醫療袋)',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(119,'03 蔬果袋 (平裝 / 捲裝)','聯繫我們','',0,'03 蔬果袋 (平裝 / 捲裝)',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(120,'04 夾鏈袋 (密實袋 / 立體密實袋 / 冷凍袋 / 夾鏈袋)','聯繫我們','',0,'04 夾鏈袋 (密實袋 / 立體密實袋 / 冷凍袋 / 夾鏈袋)',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(121,'05 其他類 (手套 / 台塑遮蔽防塵膠帶)','聯繫我們','',0,'05 其他類 (手套 / 台塑遮蔽防塵膠帶)',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(122,'06 Scale Sheet / Tare Sheet','聯繫我們','',0,'06 Scale Sheet / Tare Sheet',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(123,'需求內容與訊息','聯繫我們','',0,'需求內容與訊息',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(124,'請留下您的產品需求、規格諮詢或合作方向...','聯繫我們','',0,'請留下您的產品需求、規格諮詢或合作方向...',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(125,'確認送出，我們會儘速聯繫您','聯繫我們','',0,'確認送出，我們會儘速聯繫您',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(126,'環保標章產品｜臺灣營德股份有限公司','永續發展','',0,'環保標章產品｜臺灣營德股份有限公司',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(127,'臺灣營德環保標章產品：台塑環保拉繩清潔袋與台塑環保清潔袋。','永續發展','',0,'臺灣營德環保標章產品：台塑環保拉繩清潔袋與台塑環保清潔袋。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(128,'綠色標章產品','永續發展','',0,'綠色標章產品',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(129,'讓每一次選擇，<br>更靠近綠色生活。','永續發展','',1,'讓每一次選擇，<br>更靠近綠色生活。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(130,'臺灣營德以通過環保標章的產品，回應日常生活對環境友善選擇的需求。從產品設計到使用，我們以可被辨識的綠色承諾，陪伴每一個乾淨安心的日常。','永續發展','',0,'臺灣營德以通過環保標章的產品，回應日常生活對環境友善選擇的需求。從產品設計到使用，我們以可被辨識的綠色承諾，陪伴每一個乾淨安心的日常。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(131,'認識環保標章產品','永續發展','',0,'認識環保標章產品',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(132,'環保標章介紹','永續發展','',0,'環保標章介紹',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(133,'環保標章是什麼','永續發展','',0,'環保標章是什麼',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(134,'以綠葉環抱地球，<br>辨識更友善的選擇。','永續發展','',1,'以綠葉環抱地球，<br>辨識更友善的選擇。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(135,'環保標章以綠色葉片環繞地球的意象，傳遞守護環境、珍惜資源的理念。取得標章的產品，須符合環境部公告的規格標準並獲得使用證書，讓消費者採購時有清楚的辨識依據。','永續發展','',0,'環保標章以綠色葉片環繞地球的意象，傳遞守護環境、珍惜資源的理念。取得標章的產品，須符合環境部公告的規格標準並獲得使用證書，讓消費者採購時有清楚的辨識依據。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(136,'綠色消費的觀念在歐美環保運動中逐漸發展，德國、加拿大、日本與北歐等地也陸續建立環保標章制度。台灣於民國81年推動環保標章，鼓勵製造端減少污染與資源消耗，也讓使用者能支持可回收、低污染與省資源的產品。','永續發展','',0,'綠色消費的觀念在歐美環保運動中逐漸發展，德國、加拿大、日本與北歐等地也陸續建立環保標章制度。台灣於民國81年推動環保標章，鼓勵製造端減少污染與資源消耗，也讓使用者能支持可回收、低污染與省資源的產品。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(137,'環保標章規格標準','永續發展','',0,'環保標章規格標準',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(138,'環保標章產品查詢','永續發展','',0,'環保標章產品查詢',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(139,'依 ISO 14024 原則建立','永續發展','',0,'依 ISO 14024 原則建立',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(140,'環保標章採用國際第一類環境標誌的原則與程序，以市場機制鼓勵環境衝擊較低的產品與服務。','永續發展','',0,'環保標章採用國際第一類環境標誌的原則與程序，以市場機制鼓勵環境衝擊較低的產品與服務。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(141,'從產品生命週期看環境','永續發展','',0,'從產品生命週期看環境',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(142,'原料取得、生產、銷售、使用到廢棄，各階段的減量、回收、低污染與資源效率都是重要考量。','永續發展','',0,'原料取得、生產、銷售、使用到廢棄，各階段的減量、回收、低污染與資源效率都是重要考量。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(143,'持續擴大的綠色選擇','永續發展','',0,'持續擴大的綠色選擇',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(144,'自民國82年公布首批標準以來，環保標章已涵蓋14大產品類別、超過百項產品項目。','永續發展','',0,'自民國82年公布首批標準以來，環保標章已涵蓋14大產品類別、超過百項產品項目。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(145,'我們的綠色標章產品','永續發展','',0,'我們的綠色標章產品',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(146,'兩款取得環保標章的日常用品','永續發展','',0,'兩款取得環保標章的日常用品',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(147,'產品規格與標章資訊以環境部「淨零綠生活資訊平台」公開資料為準；點選卡片可查看各產品的完整資料。','永續發展','',0,'產品規格與標章資訊以環境部「淨零綠生活資訊平台」公開資料為準；點選卡片可查看各產品的完整資料。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(148,'台塑環保拉繩清潔袋','永續發展','',0,'台塑環保拉繩清潔袋',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(149,'兼顧日常收納與清潔需求的環保標章產品。','永續發展','',0,'兼顧日常收納與清潔需求的環保標章產品。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(150,'查看環保標章產品資料','永續發展','',0,'查看環保標章產品資料',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(151,'台塑環保清潔袋','永續發展','',0,'台塑環保清潔袋',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(152,'為居家與日常清潔情境提供的環保標章產品選擇。','永續發展','',0,'為居家與日常清潔情境提供的環保標章產品選擇。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(153,'我們的作法','永續發展','',0,'我們的作法',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(154,'以務實行動，讓綠色成為日常。','永續發展','',0,'以務實行動，讓綠色成為日常。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(155,'珍惜每一份資源','永續發展','',0,'珍惜每一份資源',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(156,'我們持續將資源循環的思維帶進產品與製造流程，讓材料的價值被更充分運用。','永續發展','',0,'我們持續將資源循環的思維帶進產品與製造流程，讓材料的價值被更充分運用。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(157,'從容易辨識的選擇開始','永續發展','',0,'從容易辨識的選擇開始',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(158,'以取得環保標章的產品，讓企業與消費者在採購與生活中，多一個清楚可靠的選擇。','永續發展','',0,'以取得環保標章的產品，讓企業與消費者在採購與生活中，多一個清楚可靠的選擇。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(159,'想了解環保標章產品的採購資訊？','永續發展','',0,'想了解環保標章產品的採購資訊？',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(160,'歡迎聯繫臺灣營德團隊，我們將協助您找到合適的產品選擇。','永續發展','',0,'歡迎聯繫臺灣營德團隊，我們將協助您找到合適的產品選擇。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(161,'聯繫我們','永續發展','',0,'聯繫我們',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(162,'產品中心 | 臺灣營德股份有限公司 Inteplast Taiwan','產品中心','',0,'產品中心 | 臺灣營德股份有限公司 Inteplast Taiwan',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(163,'臺灣營德產品中心 – 核心產品系列：清潔袋、拉繩袋、蔬果袋、夾鏈袋、手套與遮蔽防塵膠帶與 Scale Sheet。全高清產品展示與 B2B 對接。','產品中心','',0,'臺灣營德產品中心 – 核心產品系列：清潔袋、拉繩袋、蔬果袋、夾鏈袋、手套與遮蔽防塵膠帶與 Scale Sheet。全高清產品展示與 B2B 對接。',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(164,'產品中心','產品中心','',0,'產品中心',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(165,'顯示全部 All','產品中心','',0,'顯示全部 All',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(168,'留下資料專人對接','產品中心','',0,'留下資料專人對接',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(170,'相關連結','共用（頁首）','',0,'相關連結',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(171,'台灣塑膠工業股份有限公司.','共用（頁首）','',0,'台灣塑膠工業股份有限公司','admin','2026-09-10T08:25:32.540Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(172,'INTEPLAST USA','共用（頁首）','',0,'INTEPLAST USA',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(173,'永續發展','共用（頁首）','',0,'永續發展',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(174,'人才招募','共用（頁首）','',0,'人才招募',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(175,'首頁','共用（頁首）','',0,'首頁',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(176,'關於營德','共用（頁首）','',0,'關於營德',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(178,'網站導覽','共用（頁尾）','',0,'網站導覽',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(179,'產品分類','共用（頁尾）','',0,'產品分類',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(180,'嘉義新港生產基地 · ISO 9001 品質管理系統認證','共用（頁尾）','',0,'嘉義新港生產基地 · ISO 9001 品質管理系統認證',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(181,'搜尋產品或用途','共用（搜尋）','',0,'搜尋產品或用途',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(182,'垃圾袋','共用（搜尋）','',0,'垃圾袋',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(183,'束口袋','共用（搜尋）','',0,'束口袋',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(184,'保鮮袋','共用（搜尋）','',0,'保鮮袋',NULL,NULL);
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(185,'耐熱袋','共用（搜尋）','',0,'蔬果袋','admin','2026-09-10T07:03:04.415Z');
INSERT INTO "ui_strings" ("id","zh","page","note","hidden","zh_key","updated_by","updated_at") VALUES(186,'手套','共用（搜尋）','',0,'手套',NULL,NULL);
CREATE TABLE page_blocks (   id         INTEGER PRIMARY KEY AUTOINCREMENT,   page       TEXT NOT NULL,                       layout     TEXT NOT NULL DEFAULT 'image-right',    eyebrow    TEXT NOT NULL DEFAULT '',            title      TEXT NOT NULL DEFAULT '',   body       TEXT NOT NULL DEFAULT '',   image      TEXT NOT NULL DEFAULT '',          caption    TEXT NOT NULL DEFAULT '',           sort_order INTEGER NOT NULL DEFAULT 0,   visible    INTEGER NOT NULL DEFAULT 1,   created_at TEXT NOT NULL DEFAULT (datetime('now')) , updated_by TEXT, updated_at TEXT);
CREATE TABLE media (   name       TEXT PRIMARY KEY,                 mime       TEXT NOT NULL DEFAULT 'image/webp',   data       TEXT NOT NULL,                    bytes      INTEGER NOT NULL DEFAULT 0,   width      INTEGER NOT NULL DEFAULT 0,   height     INTEGER NOT NULL DEFAULT 0,   created_at TEXT NOT NULL DEFAULT (datetime('now')) );
CREATE TABLE site_images (   id         INTEGER PRIMARY KEY AUTOINCREMENT,   key        TEXT NOT NULL UNIQUE,   label      TEXT NOT NULL DEFAULT '',   hint       TEXT NOT NULL DEFAULT '',   path       TEXT NOT NULL DEFAULT '',   fallback   TEXT NOT NULL DEFAULT '',   sort_order INTEGER NOT NULL DEFAULT 0,   updated_by TEXT,   updated_at TEXT );
INSERT INTO "site_images" ("id","key","label","hint","path","fallback","sort_order","updated_by","updated_at") VALUES(1,'sus_product_drawtape','永續頁：台塑環保拉繩清潔袋','永續發展頁「環保標章認證產品」左邊那張。橫幅裁切，建議 1600×1000 以上','/media/drawtape.webp','src/opt/drawtape.jpg',1,'sales','2026-09-09T05:37:37.543Z');
INSERT INTO "site_images" ("id","key","label","hint","path","fallback","sort_order","updated_by","updated_at") VALUES(2,'sus_product_cleaning','永續頁：台塑環保清潔袋','永續發展頁「環保標章認證產品」右邊那張。橫幅裁切，建議 1600×1000 以上','/media/cleaning.webp','src/opt/cleaning.jpg',2,'sales','2026-09-09T05:37:37.550Z');
INSERT INTO "site_images" ("id","key","label","hint","path","fallback","sort_order","updated_by","updated_at") VALUES(3,'eco_certificate','環保標章使用證書','首頁與永續發展頁都用這一張。換掉前請確認是最新版證書','/media/combine.webp','src/opt/combine.jpg',3,'sales','2026-09-09T05:37:37.546Z');
INSERT INTO "site_images" ("id","key","label","hint","path","fallback","sort_order","updated_by","updated_at") VALUES(4,'about_hero','關於營德：頁首背景照','關於營德最上方的全幅背景（製袋區）。以右下角為基準裁切，建議 2000px 寬以上的橫幅','/media/%E8%A3%BD%E8%A2%8B%E5%8D%80.webp','src/製袋區.jpeg',4,'sales','2026-09-09T05:37:37.547Z');
INSERT INTO "site_images" ("id","key","label","hint","path","fallback","sort_order","updated_by","updated_at") VALUES(5,'about_awards','關於營德：卓越獎項照片','「連續五年獲頒卓越獎」旁邊的獎座照。白底棚拍，建議 1200×900 以上','/media/excellence-awards.webp','src/excellence-awards.jpg',5,'sales','2026-09-09T05:37:37.530Z');
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('products',8);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('timeline',13);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('synonyms',83);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('settings',8);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('translations',529);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('synonym_suggestions',37);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('inquiries',1);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('ui_strings',186);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('page_blocks',7);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('site_images',5);
CREATE INDEX idx_synonyms_product ON synonyms (product_id);
CREATE INDEX idx_tr_lookup ON translations (entity, lang, entity_id);
CREATE INDEX idx_sugg_status ON synonym_suggestions (status, product_id);
CREATE INDEX idx_inq_status ON inquiries (status, id);
CREATE INDEX idx_ui_page ON ui_strings (page);
CREATE INDEX idx_blocks_page ON page_blocks (page, sort_order);
