-- 介面文字匯入 第 1 / 3 批（130 條）
-- 依序執行 v6-1 → v6-2 → …，每個檔案整份貼進 D1 Console 按 Execute

INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('臺灣營德股份有限公司 | INTEPLAST TAIWAN CORPORATION', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('臺灣營德股份有限公司 (INTEPLAST TAIWAN CORPORATION) 為台塑關係企業與 INTEPLAST USA 合資大廠，專業生產清潔袋、拉繩袋、蔬果袋、夾鏈袋、手套/遮蔽膠帶與 Scale Sheet，提供多元日常與工業應用情境。', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('台塑企業清潔袋專業製造', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('台塑企業、INTEPLAST USA 與長庚生技合資建立公司。以台塑原料自製清潔袋與拉繩袋，嘉義新港、越南基地自動化吹膜；另有蔬果袋、夾鏈袋，以及集團專利抽取式 Scale Sheet。', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('瀏覽核心產品系列', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('年 (1983-{{year}})', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('{{years}} 年全球品牌資歷', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('INTEPLAST USA 1983 創立 · 2014 在台建立公司', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('品質管理系統認證', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('ISO 9001:2015 嚴格把關', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('廠內廢料閉環回收', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('100% 邊角料即時粉碎造粒', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('CORE PRODUCTS · 核心產品系列', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('核心產品系列', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('全線產品皆以台塑原料自製，嘉義新港基地一貫作業，從家用清潔袋到集團專利 Scale Sheet。', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('ENVIRONMENTAL LABEL PRODUCTS · 綠色標章產品', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('環保不打折，每一款都經過層層把關', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('台塑環保拉繩清潔袋與台塑環保清潔袋，皆通過環保標章審查並取得使用證書；從原料到製程，將環境考量落實於日常使用。', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('環保標章認證產品', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('通過環境審查', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('符合環保標章規格標準，取得產品標示資格。', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('50% 再生塑膠', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('減少對原生塑膠資源的依賴，延續材料價值。', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('避用重金屬', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('不使用鉛、鎘、汞及六價鉻等重金屬。', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('製程審慎管理', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('避用列管毒性化學物質及相關管制物。', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('查看更多', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('留下聯絡資料，我們將由專人與您聯繫', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('無論是產品規格諮詢、外銷配合或客製化需求，歡迎留下資訊，我們將有專人與您對接。', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('留下聯絡資料', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('清潔袋 · 拉繩袋 · 蔬果袋...', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('綠色標章認證', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('50% 再生塑膠 · 避用重金屬', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('聯繫專人窗口', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('留下資料 · 由專人與您對接', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('快速篩選：', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES (''' + esc(s) + ''', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES (''' + esc(tw.main) + ''', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('又稱 '' + esc(tw.alias) + ''', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES (''' + esc(row.highlight) + ''', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('前往產品中心查看', '首頁');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('認識臺灣營德股份有限公司：從台塑新港廠到 INTEPLAST GROUP 全球製造網絡，超過三十年的塑膠薄膜、清潔袋與軟包裝製造歷程。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('關於臺灣營德｜從新港出發的全球製造實力', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('從台灣出發，為世界製造', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('在新港，我們把穩定品質、精密製程與環境思維，做成全球市場可以信賴的日常。臺灣營德持續用更好的製造，回應每一個正在前進的需求。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('整合全球技術與在地根基，讓製造更有韌性', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('臺灣營德站在新港，串連 INTEPLAST GROUP 的全球加工經驗與台塑公司的原料、廠區資源；把三方力量，轉化為客戶可依賴的製造能力。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('全球塑膠加工技術、製造管理與跨市場服務網絡。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('美國總部｜北美、亞洲、歐洲製造版圖', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('前往 INTEPLAST GROUP 官網', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('臺灣營德', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('在嘉義新港，把原料、技術與製程整合為穩定可靠的薄膜與軟包裝解決方案。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('共同投資夥伴：INTEPLAST GROUP、台灣塑膠公司、長庚生物科技', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('與臺灣營德聯繫', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('台灣塑膠公司', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('穩定的原料資源與台塑企業新港廠區產業基礎，支撐高效率且穩定的生產配置。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('台灣塑膠公司｜台塑企業成員', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('前往台灣塑膠公司官網', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('三方共同投資，讓臺灣營德兼具國際製造視野、在地供應韌性與長期經營基礎。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('從台塑到營德，厚植製造實力', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('臺灣營德的製造故事，源自台塑塑膠加工組。1983 年，加工組於高雄前鎮廠起步，開始生產購物袋；1984 年，市場袋、清潔袋正式加入產品線，逐步累積袋品製造的基礎與經驗。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('1989 年，新港廠整地擴建；1991 年正式投產，並啟用全自動拌料輸送系統。隨著市場需求與設備能力提升，產品線也持續延伸。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('2004 年，前鎮廠遷廠合併，新港成為主要生產基地；2008 年，全球產品配置重整，讓製造資源更聚焦於具技術與品質優勢的產品。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('2014 年，台塑塑膠加工組改組，成立「臺灣營德股份有限公司」。臺灣營德延續既有的製造經驗，結合 INTEPLAST GROUP 的全球技術與營運管理，並持續作為台塑相關企業的一員，開啟新的篇章。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('2015 年，越南營德公司成立，進一步拓展海外製造布局。透過臺灣與越南生產基地的相互支援，結合 INTEPLAST GROUP 的全球資源與技術經驗，逐步強化產能配置與國際市場供應能力。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('從前鎮的第一只購物袋，到新港的持續精進；我們把累積多年的製造經驗，轉化為面向未來的可靠承諾。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('臺灣營德的製造歷程', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('故事始於高雄前鎮廠，從袋品生產出發，逐步發展為今日的製造基地。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('集團肯定，來自實際的生產表現', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('臺灣營德連續五年獲頒 INTEPLAST GROUP Excellence Award 卓越獎。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('INTEPLAST GROUP 卓越獎與年度最大進步營運單位獎座', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('抽取式設計，取得美國專利', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('Scale Sheet 的單張抽取結構已取得美國專利。取用一張就是一張，不必翻找、不會沾黏，讓秤重與分裝的每一次動作都省下時間。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('不只是製造，更是對品質與未來的承諾', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('從自動化生產、跨市場產品開發到循環再利用，我們把三十餘年的現場經驗轉化為客戶可以信賴的製造能力。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('讓穩定品質，成為製程的日常', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('從全自動拌料與原料空輸，到 PLC 吹膜控制與精密點斷熱封，每一道製程都為穩定品質與良率而設計。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('製程 × 品質管理', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('以多元產品，回應全球市場', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('從捲膜、清潔袋、拉繩袋到醫療包裝與冷凍密實袋，臺灣營德服務台灣、日本、美洲與東南亞等市場。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('產品 × 市場連結', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('把永續，落實在每個細節', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('採用環保水性墨、建構廢膜回收再生系統，並推出取得國家環保標章認證的綠色產品。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('材料 × 循環思維', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('把現場經驗，轉化成每一批產品的可靠度', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('新港基地將原料輸送、吹膜、印刷、製袋與品質控管串聯為完整流程，讓品質不是最後一道檢查，而是每一道製程的共同標準。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('全自動拌料與原料空輸', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('PLC 自動化吹膜控制', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('精密點斷、熱封與品質追蹤', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('下一段製造故事，與您一起開始', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('需要穩定可靠的塑膠薄膜、袋品或軟包裝製造夥伴？讓臺灣營德的技術與全球網絡，回應您的產品需求。', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('聯繫與詢價', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('瀏覽產品中心', '關於營德');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('聯繫我們 | 臺灣營德股份有限公司 INTEPLAST TAIWAN CORPORATION', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('聯繫臺灣營德股份有限公司 (INTEPLAST TAIWAN) 外銷業務團隊。地址：臺北市松山區敦化北路205號6樓609室，電話：02-2712-2211 #8109。', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('聯繫臺灣營德', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('留下聯絡資料由我們主動與您聯繫，或直接聯絡營德專人窗口。', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('直接聯繫營德窗口', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('留下資料 · 由我們聯繫您', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('聯絡我們', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('公司地址', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('臺北市松山區敦化北路205號6樓609室', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('連絡電話', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('服務時間：週一至週五 08:30–17:30（國定假日休息）', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('電子郵件', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('撥打電話', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('寄送 Email 諮詢', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('留下您的聯絡資料', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('公司名稱', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('例：Global Packaging Co., Ltd.', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('商務信箱（必填）', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('name@yourcompany.com', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('聯絡電話（選填）', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('例：02-2712-2211 或 0912-345-678', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('詢問產品類別', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('01 清潔袋 (連捲 / 單張抽取 / 環保)', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('02 拉繩袋 (清潔袋 / 醫療袋)', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('03 蔬果袋 (平裝 / 捲裝)', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('04 夾鏈袋 (密實袋 / 立體密實袋 / 冷凍袋 / 夾鏈袋)', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('05 其他類 (手套 / 台塑遮蔽防塵膠帶)', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('06 Scale Sheet / Tare Sheet', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('需求內容與訊息', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('請留下您的產品需求、規格諮詢或合作方向...', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('確認送出，我們會儘速聯繫您', '聯繫我們');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('環保標章產品｜臺灣營德股份有限公司', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('臺灣營德環保標章產品：台塑環保拉繩清潔袋與台塑環保清潔袋。', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('綠色標章產品', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('讓每一次選擇，<br>更靠近綠色生活。', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('臺灣營德以通過環保標章的產品，回應日常生活對環境友善選擇的需求。從產品設計到使用，我們以可被辨識的綠色承諾，陪伴每一個乾淨安心的日常。', '永續發展');
