-- 介面文字匯入 第 2 / 3 批（130 條）
-- 依序執行 v6-1 → v6-2 → …，每個檔案整份貼進 D1 Console 按 Execute

INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('認識環保標章產品', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('環保標章介紹', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('環保標章是什麼', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('以綠葉環抱地球，<br>辨識更友善的選擇。', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('環保標章以綠色葉片環繞地球的意象，傳遞守護環境、珍惜資源的理念。取得標章的產品，須符合環境部公告的規格標準並獲得使用證書，讓消費者採購時有清楚的辨識依據。', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('綠色消費的觀念在歐美環保運動中逐漸發展，德國、加拿大、日本與北歐等地也陸續建立環保標章制度。台灣於民國81年推動環保標章，鼓勵製造端減少污染與資源消耗，也讓使用者能支持可回收、低污染與省資源的產品。', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('環保標章規格標準', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('環保標章產品查詢', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('依 ISO 14024 原則建立', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('環保標章採用國際第一類環境標誌的原則與程序，以市場機制鼓勵環境衝擊較低的產品與服務。', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('從產品生命週期看環境', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('原料取得、生產、銷售、使用到廢棄，各階段的減量、回收、低污染與資源效率都是重要考量。', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('持續擴大的綠色選擇', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('自民國82年公布首批標準以來，環保標章已涵蓋14大產品類別、超過百項產品項目。', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('我們的綠色標章產品', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('兩款取得環保標章的日常用品', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('產品規格與標章資訊以環境部「淨零綠生活資訊平台」公開資料為準；點選卡片可查看各產品的完整資料。', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('台塑環保拉繩清潔袋', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('兼顧日常收納與清潔需求的環保標章產品。', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('查看環保標章產品資料', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('台塑環保清潔袋', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('為居家與日常清潔情境提供的環保標章產品選擇。', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('我們的作法', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('以務實行動，讓綠色成為日常。', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('珍惜每一份資源', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('我們持續將資源循環的思維帶進產品與製造流程，讓材料的價值被更充分運用。', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('從容易辨識的選擇開始', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('以取得環保標章的產品，讓企業與消費者在採購與生活中，多一個清楚可靠的選擇。', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('想了解環保標章產品的採購資訊？', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('歡迎聯繫臺灣營德團隊，我們將協助您找到合適的產品選擇。', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('聯繫我們', '永續發展');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('產品中心 | 臺灣營德股份有限公司 Inteplast Taiwan', '產品中心');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('臺灣營德產品中心 – 核心產品系列：清潔袋、拉繩袋、蔬果袋、夾鏈袋、手套與遮蔽防塵膠帶與 Scale Sheet。全高清產品展示與 B2B 對接。', '產品中心');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('產品中心', '產品中心');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('顯示全部 All', '產品中心');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES (''' + esc(cat.highlight) + ''', '產品中心');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES (''' + esc(cat.desc) + ''', '產品中心');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('留下資料專人對接', '產品中心');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES (''' + esc(noStr + '' '' + nameTw) + ''', '產品中心');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('相關連結', '共用（頁首）');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('台灣塑膠工業股份有限公司', '共用（頁首）');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('INTEPLAST USA', '共用（頁首）');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('永續發展', '共用（頁首）');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('人才招募', '共用（頁首）');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('首頁', '共用（頁首）');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('關於營德', '共用（頁首）');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES (''' + tw + ''', '共用（頁尾）');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('網站導覽', '共用（頁尾）');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('產品分類', '共用（頁尾）');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('嘉義新港生產基地 · ISO 9001 品質管理系統認證', '共用（頁尾）');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('搜尋產品或用途', '共用（搜尋）');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('垃圾袋', '共用（搜尋）');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('束口袋', '共用（搜尋）');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('保鮮袋', '共用（搜尋）');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('蔬果袋', '共用（搜尋）');
INSERT OR IGNORE INTO ui_strings (zh, page) VALUES ('手套', '共用（搜尋）');
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'INTEPLAST TAIWAN CORPORATION | Can Liner, Draw Tape & Zipper Bag Manufacturer' FROM ui_strings WHERE zh = '臺灣營德股份有限公司 | INTEPLAST TAIWAN CORPORATION';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'INTEPLAST TAIWAN CORPORATION is a joint venture of Formosa Plastics and INTEPLAST USA, manufacturing can liners, draw tape liners, produce bags, zipper bags, gloves, masking film and Scale Sheet for household and industrial use.' FROM ui_strings WHERE zh = '臺灣營德股份有限公司 (INTEPLAST TAIWAN CORPORATION) 為台塑關係企業與 INTEPLAST USA 合資大廠，專業生產清潔袋、拉繩袋、蔬果袋、夾鏈袋、手套/遮蔽膠帶與 Scale Sheet，提供多元日常與工業應用情境。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Formosa Plastics Group · Can Liner Specialist' FROM ui_strings WHERE zh = '台塑企業清潔袋專業製造';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'A joint venture of Formosa Plastics, INTEPLAST USA and Chang Gung Biotech. Built on Formosa resin, our Chiayi Xingang and Vietnam plants run automated extrusion for can liners and draw-tape bags, alongside produce and zipper bags, plus the group''s patented pop-up Scale Sheet.' FROM ui_strings WHERE zh = '台塑企業、INTEPLAST USA 與長庚生技合資建立公司。以台塑原料自製清潔袋與拉繩袋，嘉義新港、越南基地自動化吹膜；另有蔬果袋、夾鏈袋，以及集團專利抽取式 Scale Sheet。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Explore Our Product Lines' FROM ui_strings WHERE zh = '瀏覽核心產品系列';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Yrs (1983-{{year}})' FROM ui_strings WHERE zh = '年 (1983-{{year}})';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', '{{years}} Years Group History' FROM ui_strings WHERE zh = '{{years}} 年全球品牌資歷';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Founded 1983 · Taiwan Company Est. 2014' FROM ui_strings WHERE zh = 'INTEPLAST USA 1983 創立 · 2014 在台建立公司';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'ISO 9001:2015 Certified' FROM ui_strings WHERE zh = '品質管理系統認證';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'ISO 9001 Quality Control' FROM ui_strings WHERE zh = 'ISO 9001:2015 嚴格把關';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'In-House Scrap Recycling' FROM ui_strings WHERE zh = '廠內廢料閉環回收';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', '100% Zero Waste Recycling' FROM ui_strings WHERE zh = '100% 邊角料即時粉碎造粒';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'CORE PRODUCTS' FROM ui_strings WHERE zh = 'CORE PRODUCTS · 核心產品系列';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Core Products' FROM ui_strings WHERE zh = '核心產品系列';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Every line is built on Formosa resin and produced in-house at our Chiayi Xingang plant — from household can liners to the group''s patented Scale Sheet.' FROM ui_strings WHERE zh = '全線產品皆以台塑原料自製，嘉義新港基地一貫作業，從家用清潔袋到集團專利 Scale Sheet。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'ENVIRONMENTAL LABEL PRODUCTS' FROM ui_strings WHERE zh = 'ENVIRONMENTAL LABEL PRODUCTS · 綠色標章產品';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Uncompromised Eco Quality, Rigorously Audited' FROM ui_strings WHERE zh = '環保不打折，每一款都經過層層把關';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Formosa Eco Drawtape and Can Liner bags are fully Green Mark certified from raw materials to manufacturing.' FROM ui_strings WHERE zh = '台塑環保拉繩清潔袋與台塑環保清潔袋，皆通過環保標章審查並取得使用證書；從原料到製程，將環境考量落實於日常使用。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'ENVIRONMENTAL LABEL CERTIFIED' FROM ui_strings WHERE zh = '環保標章認證產品';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Passed Environmental Audits' FROM ui_strings WHERE zh = '通過環境審查';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Meets official Green Mark specifications.' FROM ui_strings WHERE zh = '符合環保標章規格標準，取得產品標示資格。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', '50% Recycled Plastic' FROM ui_strings WHERE zh = '50% 再生塑膠';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Reduces reliance on virgin plastics.' FROM ui_strings WHERE zh = '減少對原生塑膠資源的依賴，延續材料價值。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Zero Heavy Metals' FROM ui_strings WHERE zh = '避用重金屬';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Free of lead, cadmium, mercury, and hexavalent chromium.' FROM ui_strings WHERE zh = '不使用鉛、鎘、汞及六價鉻等重金屬。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Strict Process Control' FROM ui_strings WHERE zh = '製程審慎管理';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Free of regulated toxic chemical substances.' FROM ui_strings WHERE zh = '避用列管毒性化學物質及相關管制物。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Read More' FROM ui_strings WHERE zh = '查看更多';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Leave Your Contact Details & We Will Be In Touch' FROM ui_strings WHERE zh = '留下聯絡資料，我們將由專人與您聯繫';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Leave your inquiries and contact details, and our sales team will reach out to you.' FROM ui_strings WHERE zh = '無論是產品規格諮詢、外銷配合或客製化需求，歡迎留下資訊，我們將有專人與您對接。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Leave Contact Details' FROM ui_strings WHERE zh = '留下聯絡資料';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Can Liners, Drawtape...' FROM ui_strings WHERE zh = '清潔袋 · 拉繩袋 · 蔬果袋...';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Green Mark Certification' FROM ui_strings WHERE zh = '綠色標章認證';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', '50% Recycled Plastic' FROM ui_strings WHERE zh = '50% 再生塑膠 · 避用重金屬';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Contact Us Desk' FROM ui_strings WHERE zh = '聯繫專人窗口';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Leave Info & We Contact' FROM ui_strings WHERE zh = '留下資料 · 由專人與您對接';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Quick Tags:' FROM ui_strings WHERE zh = '快速篩選：';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', ''' + esc(e) + ''' FROM ui_strings WHERE zh = ''' + esc(s) + ''';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', ''' + esc(en.main) + ''' FROM ui_strings WHERE zh = ''' + esc(tw.main) + ''';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Also known as '' + esc(en.alias || tw.alias) + ''' FROM ui_strings WHERE zh = '又稱 '' + esc(tw.alias) + ''';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', ''' + esc(row.highlight_en || row.highlight) + ''' FROM ui_strings WHERE zh = ''' + esc(row.highlight) + ''';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'View in Product Center' FROM ui_strings WHERE zh = '前往產品中心查看';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'INTEPLAST TAIWAN CORPORATION: from the Formosa Plastics Xingang plant to the INTEPLAST GROUP global network, over thirty years of plastic film, can liner and flexible packaging manufacturing.' FROM ui_strings WHERE zh = '認識臺灣營德股份有限公司：從台塑新港廠到 INTEPLAST GROUP 全球製造網絡，超過三十年的塑膠薄膜、清潔袋與軟包裝製造歷程。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'About INTEPLAST TAIWAN | Global Manufacturing from Xingang, Chiayi' FROM ui_strings WHERE zh = '關於臺灣營德｜從新港出發的全球製造實力';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Made in Taiwan. Built for the world.' FROM ui_strings WHERE zh = '從台灣出發，為世界製造';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'In Xingang, we turn reliable quality, precise processes, and environmental thinking into work global markets can count on—responding to every need that keeps moving forward.' FROM ui_strings WHERE zh = '在新港，我們把穩定品質、精密製程與環境思維，做成全球市場可以信賴的日常。臺灣營德持續用更好的製造，回應每一個正在前進的需求。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'A manufacturing network built for more' FROM ui_strings WHERE zh = '整合全球技術與在地根基，讓製造更有韌性';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'From Xingang, INTEPLAST TAIWAN connects INTEPLAST GROUP''s global processing expertise with Formosa Plastics'' materials and industrial resources—turning shared strength into dependable manufacturing.' FROM ui_strings WHERE zh = '臺灣營德站在新港，串連 INTEPLAST GROUP 的全球加工經驗與台塑公司的原料、廠區資源；把三方力量，轉化為客戶可依賴的製造能力。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Global plastics processing, manufacturing management and market reach.' FROM ui_strings WHERE zh = '全球塑膠加工技術、製造管理與跨市場服務網絡。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'U.S. headquarters | Manufacturing across North America, Asia and Europe' FROM ui_strings WHERE zh = '美國總部｜北美、亞洲、歐洲製造版圖';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Visit INTEPLAST GROUP' FROM ui_strings WHERE zh = '前往 INTEPLAST GROUP 官網';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'INTEPLAST TAIWAN' FROM ui_strings WHERE zh = '臺灣營德';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'In Xingang, we integrate materials, technology and processes into reliable film and flexible packaging solutions.' FROM ui_strings WHERE zh = '在嘉義新港，把原料、技術與製程整合為穩定可靠的薄膜與軟包裝解決方案。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Jointly invested by INTEPLAST GROUP, Formosa Plastics and Chang Gung Biotechnology' FROM ui_strings WHERE zh = '共同投資夥伴：INTEPLAST GROUP、台灣塑膠公司、長庚生物科技';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Contact INTEPLAST TAIWAN' FROM ui_strings WHERE zh = '與臺灣營德聯繫';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Formosa Plastics Corporation' FROM ui_strings WHERE zh = '台灣塑膠公司';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Reliable material resources and the industrial foundation of the Xingang complex support efficient, stable production.' FROM ui_strings WHERE zh = '穩定的原料資源與台塑企業新港廠區產業基礎，支撐高效率且穩定的生產配置。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Formosa Plastics Corporation | Formosa Plastics Group member' FROM ui_strings WHERE zh = '台灣塑膠公司｜台塑企業成員';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Visit Formosa Plastics' FROM ui_strings WHERE zh = '前往台灣塑膠公司官網';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Joint investment gives INTEPLAST TAIWAN global manufacturing perspective, local supply resilience, and a foundation for long-term growth.' FROM ui_strings WHERE zh = '三方共同投資，讓臺灣營德兼具國際製造視野、在地供應韌性與長期經營基礎。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'From Formosa Plastics to INTEPLAST TAIWAN—strengthening manufacturing expertise' FROM ui_strings WHERE zh = '從台塑到營德，厚植製造實力';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'INTEPLAST TAIWAN''s manufacturing story traces back to Formosa Plastics'' processing group. In 1983, the group began at the Kaohsiung Qianzhen plant with shopping bag production; produce bags and can liners followed in 1984, building the foundation for decades of bag manufacturing expertise.' FROM ui_strings WHERE zh = '臺灣營德的製造故事，源自台塑塑膠加工組。1983 年，加工組於高雄前鎮廠起步，開始生產購物袋；1984 年，市場袋、清潔袋正式加入產品線，逐步累積袋品製造的基礎與經驗。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Xingang expanded in 1989 and began production in 1991 with an automated mixing and conveying system. As market demand and capability grew, the product portfolio continued to expand.' FROM ui_strings WHERE zh = '1989 年，新港廠整地擴建；1991 年正式投產，並啟用全自動拌料輸送系統。隨著市場需求與設備能力提升，產品線也持續延伸。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'In 2004, the Qianzhen operation was consolidated and Xingang became the primary production base. A 2008 global product realignment sharpened the focus on products with technical and quality advantages.' FROM ui_strings WHERE zh = '2004 年，前鎮廠遷廠合併，新港成為主要生產基地；2008 年，全球產品配置重整，讓製造資源更聚焦於具技術與品質優勢的產品。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'In 2014, the Formosa Plastics processing group was reorganized as INTEPLAST TAIWAN CORPORATION. Building on its manufacturing experience and INTEPLAST GROUP''s global technology and operations, INTEPLAST TAIWAN continues as part of the Formosa Plastics affiliated enterprise network.' FROM ui_strings WHERE zh = '2014 年，台塑塑膠加工組改組，成立「臺灣營德股份有限公司」。臺灣營德延續既有的製造經驗，結合 INTEPLAST GROUP 的全球技術與營運管理，並持續作為台塑相關企業的一員，開啟新的篇章。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'In 2015, INTEPLAST VIETNAM was established, extending the manufacturing footprint overseas. With the Taiwan and Vietnam plants supporting each other and drawing on INTEPLAST GROUP''s global resources and technical experience, capacity planning and international supply capability continued to strengthen.' FROM ui_strings WHERE zh = '2015 年，越南營德公司成立，進一步拓展海外製造布局。透過臺灣與越南生產基地的相互支援，結合 INTEPLAST GROUP 的全球資源與技術經驗，逐步強化產能配置與國際市場供應能力。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'From the first shopping bag in Qianzhen to continuous progress in Xingang, we turn years of manufacturing experience into a dependable promise for the future.' FROM ui_strings WHERE zh = '從前鎮的第一只購物袋，到新港的持續精進；我們把累積多年的製造經驗，轉化為面向未來的可靠承諾。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'A manufacturing history in Taiwan' FROM ui_strings WHERE zh = '臺灣營德的製造歷程';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'The story began at the Kaohsiung Qianzhen plant, growing from bag production into today''s manufacturing base.' FROM ui_strings WHERE zh = '故事始於高雄前鎮廠，從袋品生產出發，逐步發展為今日的製造基地。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'Recognised for what the lines actually deliver' FROM ui_strings WHERE zh = '集團肯定，來自實際的生產表現';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'INTEPLAST TAIWAN has received the INTEPLAST GROUP Excellence Award for five consecutive years.' FROM ui_strings WHERE zh = '臺灣營德連續五年獲頒 INTEPLAST GROUP Excellence Award 卓越獎。';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'INTEPLAST GROUP Excellence Awards and The Most Improved Operation trophy' FROM ui_strings WHERE zh = 'INTEPLAST GROUP 卓越獎與年度最大進步營運單位獎座';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'A pop-up design, patented in the United States' FROM ui_strings WHERE zh = '抽取式設計，取得美國專利';
INSERT OR IGNORE INTO translations (entity, entity_id, field, lang, value) SELECT 'ui', id, 'text', 'en', 'The single-sheet pop-up structure behind Scale Sheet is protected by a United States patent. One pull, one sheet — no fumbling, no sticking, and time saved on every weigh and repack.' FROM ui_strings WHERE zh = 'Scale Sheet 的單張抽取結構已取得美國專利。取用一張就是一張，不必翻找、不會沾黏，讓秤重與分裝的每一次動作都省下時間。';
